### ISSUE TITLE
Cannot parse missing logs after upgrade - KeyError http

### ISSUE THREAD

**Issue by toddocon** [Autodesk/hubble#198]
We just upgraded to 2.18.8 and see this now when running Hubble. Maybe because the old (pre-upgrade) logs were moved. Certainly github-audit.log.1*.gz does not exist.

The KeyError: 'http' is an interesting one. Again, maybe related to missing logs?

```
...
gzip: /var/log/github-audit.log.1*.gz: No such file or directory

gzip: /var/log/haproxy.log.1*.gz: No such file or directory
Use of uninitialized value in new at -e line 1.

gzip: /var/log/haproxy.log.1*.gz: No such file or directory
Use of uninitialized value in new at -e line 1.

/git/tmpdata/hubble-data/git-download.tsv
/git/tmpdata/hubble-data/git-download-detailed.tsv
Finished update of git-download.tsv (runtime: 1.721 s)
Started update of git-protocol.tsv
gzip: /var/log/babeld/babeld.log.1*.gz: No such file or directory

gzip: /var/log/babeld/babeld.log.1*.gz: No such file or directory

Traceback (most recent call last):
  File "./update-stats.py", line 121, in <module>
    main()
  File "./update-stats.py", line 84, in main
    ReportGitProtocol(configuration, dataDirectory, metaStats).update()
  File "/apps/git/GitHubInsights/updater/reports/Report.py", line 168, in update
    self.updateData()
  File "/apps/git/GitHubInsights/updater/reports/ReportDaily.py", line 35, in updateData
    self.updateDailyData()
  File "/apps/git/GitHubInsights/updater/reports/ReportGitProtocol.py", line 20, in updateDailyData
    protocols["http"],
KeyError: 'http'
```

**Comment by toddocon** [comment]
I updated to the latest Hubble just now and re-ran the data gather. It worked. We still have no rotated logs to parse, though, due to the very recent upgrade.

**Comment by toddocon** [comment]
Maybe this is similar to #69 ?
