### ISSUE TITLE
Issue while running the code on 3.1.0

### ISSUE THREAD

**Issue by pramodhm112** [Autodesk/hubble#232]
- Error is as shown below

/tmp/hubble-data/orgs-total.tsv
Finished update of orgs-total.tsv (runtime: 1.276 s)
Started update of pull-requests-by-organization.tsv
mysql: [Warning] Using a password on the command line interface can be insecure.

mysql: [Warning] Using a password on the command line interface can be insecure.

/tmp/hubble-data/pull-requests-by-organization.tsv
Finished update of pull-requests-by-organization.tsv (runtime: 1.297 s)
Started update of pull-requests-by-repository.tsv
mysql: [Warning] Using a password on the command line interface can be insecure.
failed to exec into task: unexpected EOF

Traceback (most recent call last):
  File "update-stats.py", line 125, in <module>
    main()
  File "update-stats.py", line 97, in main
    ReportPRByRepo(configuration, dataDirectory, metaStats).update()
  File "/home/admin/graph-data/updater/reports/Report.py", line 168, in update
    self.updateData()
  File "/home/admin/graph-data/updater/reports/ReportPRByRepo.py", line 15, in updateData
    self.executeQuery(self.query([self.daysAgo(30), self.yesterday()])))
  File "/home/admin/graph-data/updater/reports/Report.py", line 100, in executeQuery
    return self.executeScript(self.configuration["databaseCommand"], stdin = query)
  File "/home/admin/graph-data/updater/reports/Report.py", line 85, in executeScript
    stdout, stderr = executeCommand(script, stdin)
  File "/home/admin/graph-data/updater/helpers.py", line 22, in executeCommand
    raise RuntimeError(command[0] + " failed with exit code " + str(process.returncode))
RuntimeError: ghe-dbconsole failed with exit code 1

**Comment by pramodhm112** [comment]
Hi @larsxschneider @toddocon 

Please suggest the changes to be made in the code. The code is breaking in 3.1.0 GHES Version

**Comment by vaishnav-canarys** [comment]
Hi 

Facing the same in my instance 
GHES Version: 3.1.0

failed to exec into task: unexpected EOF

Traceback (most recent call last):
  File "update-stats.py", line 119, in <module>
    main()
  File "update-stats.py", line 94, in main
    ReportPRUsage(configuration, dataDirectory, metaStats).update()
  File "/opt/autodesk/hubble-enterprise/reports/Report.py", line 168, in update
    self.updateData()
  File "/opt/autodesk/hubble-enterprise/reports/ReportDaily.py", line 35, in updateData
    self.updateDailyData()
  File "/opt/autodesk/hubble-enterprise/reports/ReportPRUsage.py", line 21, in updateDailyData
    _, newData = self.parseData(self.executeQuery(self.query(date)))
  File "/opt/autodesk/hubble-enterprise/reports/Report.py", line 100, in executeQuery
    return self.executeScript(self.configuration["databaseCommand"], stdin = query)
  File "/opt/autodesk/hubble-enterprise/reports/Report.py", line 85, in executeScript
    stdout, stderr = executeCommand(script, stdin)
  File "/opt/autodesk/hubble-enterprise/helpers.py", line 22, in executeCommand
    raise RuntimeError(command[0] + " failed with exit code " + str(process.returncode))
RuntimeError: ghe-dbconsole failed with exit code 1

**Comment by pluehne** [comment]
@pramodhm112, @vaishnav-canarys: I assume that these issues are fixed in the lasted version of `master`, as I can’t reproduce it anymore. Can you confirm this? I’m going to close this issue, but please reopen it if the issue persists.
