### ISSUE TITLE
SQL syntax error introduced by Pull Request GH-5

### ISSUE THREAD

**Issue by rashamalek** [Autodesk/hubble#6]
Latest change on  PR #5 file hubble/updater/reports/ReportForksToOrgs.py lead to SQL exception.
GHE Version 2.11.2

```
ERROR 1064 (42000) at line 2: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CAST(repos.created_at AS date) AS "creation date"
			FROM
				users AS orgs,
			' at line 3

Traceback (most recent call last):
  File "update-stats.py", line 99, in <module>
    main()
  File "update-stats.py", line 72, in main
    ReportForksToOrgs(configuration, dataDirectory, metaStats).update()
  File "~/Workspace/hubble/updater/reports/Report.py", line 173, in update
    self.updateData()
  File "~/Workspace/hubble/updater/reports/ReportDaily.py", line 35, in updateData
    self.updateDailyData()
  File "~/Workspace/hubble/updater/reports/ReportForksToOrgs.py", line 13, in updateDailyData
    self.detailedHeader, self.detailedData = self.parseData(self.executeQuery(self.query()))
  File "~/Workspace/hubble/updater/reports/Report.py", line 105, in executeQuery
    return self.executeScript(self.configuration["databaseCommand"], stdin = query)
  File "~/Workspace/hubble/updater/reports/Report.py", line 96, in executeScript
    stdout, stderr = executeCommand(script, stdin)
  File "~/Workspace/hubble/updater/reports/Report.py", line 23, in executeCommand
    raise RuntimeError(command[0] + " failed with exit code " + str(process.returncode))
RuntimeError: ssh failed with exit code 1
```

**Comment by pluehne** [comment]
Thanks for the quick feedback! I’ll try to replicate this issue.

**Comment by pluehne** [comment]
There was a simple syntax error, which unfortunately slipped through. I committed a patch (09f152a87290ef31a0110d212415efcc569c52f4) to the master. Would you mind testing whether the issue is fixed with this patch?

**Comment by rashamalek** [comment]
It is fixed, thanks for quick action.

**Comment by pluehne** [comment]
And thanks for bringing this to our attention and in particular for testing our software in early development 😃!
